version: '3'

services:
  lumenapp:
    container_name: lumenapp
    image: kirill/lumenapp:1.0.0
    build: ../project
    volumes:
      - ../project:/var/www/html
    ports:
      - "8000:8000"
    env_file:
      - ../project/.env
    depends_on:
      - db

  db:
    container_name: db
    image: postgres:12
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}